version: "3.8"

volumes:
  docker-volume:

services:
  #Webサーバーのコンテナ
  nginx:
    build: ./docker/nginx
    ports:
      - "8002:80"
    depends_on:
      - php-fpm
    volumes:
      - ./src/:/app
  #アプリケーションのコンテナ
  php-fpm:
    build: ./docker/php-fpm
    container_name: laravel-sample-directory-php-fpm
    volumes:
      - ./src/:/app
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./log:/var/log
  #データベースのコンテナ
  db:
    build: ./docker/db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    volumes:
      - docker-volume:/var/lib/mysql
